export const BSc = [
  "BSc Aeronautics",
  "BSc Agriculture",
  "BSc Anatom",
  "BSc Anesthesia",
  "BSc Animation",
  "BSc Anthropology",
  "BSc Aviation",
  "BSc Biochemistry",
  "BSc Biology",
  "BSc Biotechnology ",
  "BSc Botany",
  "BSc Cardiology",
  "BSc Chemistry",
  "BSc Clinical Research ",
  "BSc Computer Science",
  "BSc Ecology",
  "BSc Economics",
  "BSc Environmental Science",
  "BSc Fashion Designing",
  "BSc Food Technology",
  "BSc Forestry",
  "BSc Geography",
  "BSc Geology",
  "BSc Geology",
  "BSc Healthcare Management",
  "BSc Home Science",
  "BSc Hospitality Management",
  "BSc IT",
  "BSc Life Sciences",
  "BSc Mathematics",
  "BSc Mathematics ",
  "BSc Microbiology",
  "BSc Microbiology",
  "Bsc Molecular Biology",
  "BSc Nautical Science",
  "BSc Nursing",
  "BSc Nutrition and Dietetics",
  "BSc Physics",
  "BSc Product Design",
  "BSc Psychology",
  "BSc Radiology",
  "BSc Statistics",
  "BSc Visual Communication",
  "BSc Zoology",
];

export const Engineering = [
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Artificial intelligence",
  "Automation and Robotics",
  "Automobile Engineering",
  "Biotechnology",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Construction Engineering",
  "Electrical Engineering",
  "Electronics and Communication Engineering",
  "Environmental Engineering",
  "Environmental Engineering",
  "Food technology",
  "Genetic Engineering",
  "Geotechnical Engineering",
  "Industrial Engineering",
  "Information technology",
  "Instrumentation Engineering",
  "Manufacturing Engineering",
  "Marine Engineering",
  "Maritime Engineering",
  "Mechanical Engineering",
  "Naval Engineering",
  "Petroleum Engineering",
  "Safety Engineering",
  "Social Engineering",
  "Structural Engineering",
  "Transportation Engineering",
];

export const Medical = [
  "Cardiology",
  "Clinical Pharmacology",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Infectious Diseases",
  "Internal Medicine",
  "Neurology",
  "Neurosurgery",
  "Obstetrics and Gynecology",
  "Oncology",
  "Orthopedics",
  "Ophthalmology",
  "Pathology",
  "Pediatrics",
  "Pharmacology",
  "Preventive Medicine",
  "Radiation Oncology",
  "Rheumatology",
  "Sports Medicine",
  "Surgery",
];

const collegeData = [
  {
    name: "ABC University",
    branches: ["Computer Science", "Mechinical","Data Science","AIML"],
    website: "xyz.com",
    erplink: "rxp.com",
  },
  {
    name: "ABC University",
    branches: ["Computer Science", "Mechinical","Data Science","AIML"],
    website: "xyz.com",
    erplink: "rxp.com",
  },
];
